### ISSUE TITLE
Can I use the pintools for Windows Os ?

### ISSUE THREAD

**Issue by mehdighninoudev** [JonathanSalwan/PinTools#4]
Hi I have a question please ? since it has been a while when I am interested in analysing PE files on windows ? Can I use the pintools scripts on windows? (or simply compile their source code on windows) ?

if it is possible because I am getting some errors during compilation on windows 10. And thank u for your help

**Comment by kaitogon** [comment]
Can u please give me the full command or the full steps to compile the OverflowDetection on windows 10 please ? it will be helpful !

**Comment by mehdighninoudev** [comment]
Finaly I find the way of how to build OverflowDetection.cpp for windows with make and generate OverflowDetection.dll. It works fine with pin! 
Thank you again for these amazing binary analysis tools. It's so much good knowledge

**Comment by JonathanSalwan** [comment]
So can you close this thread ?

**Comment by mehdighninoudev** [comment]
Okay sure I will close this thread.
